### ISSUE TITLE
Where do I get s4a.s2e?

### ISSUE THREAD

**Issue by ghost** [NCCUCS-PLSM/scratch-mqtt#1]
> 3. Choose S4A.s2e and import it, then you will see some new blocks in More Blocks. 

Where do I get this file? It is not in this repository or in Scratch 2 Offline Editor files.

**Comment by fbukevin** [comment]
Hi,

Since this project is long time ago, I'm not sure whether S4A.s2e is still an extension of Scratch. I can share the demo one I have that was an available public source. Please check out the following link to download the bundle. 
[scratch-ext-demo.zip](https://github.com/NCCUCS-PLSM/scratch-mqtt/files/2431991/scratch-ext-demo.zip)

Please note that in the bundle the file .s2e is called A4S. It could be a naming mistake.
